site_name: Rustlings Documentation
site_url: https://dohuyhoang93.github.io/LearnRustlings
repo_url: https://github.com/dohuyhoang93/LearnRustlings
site_description: Comprehensive notes on understanding Rustlings concepts and exercises
theme:
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  font:
    text: Roboto
    code: Terminus
  features:
    - toc.follow
    - toc.integrate
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.path
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols:
      trademark: true
      copyright: true
      registered: true
      care_of: true
      plusminus: true
      arrows: true
      notequal: true
      fractions: true
      ordinal_numbers: true
  - toc:
      permalink: true
      baselevel: 2
      toc_depth: 4
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      css_class: highlight
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      
  - pymdownx.arithmatex:
      generic: true
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mermaid.mjs

copyright: Copyright &copy; 2025 Do Huy Hoang

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Vietnamese
      link: ./vi/
      lang: vi